# 导入测试数据

In [1]:
from sklearn import  datasets

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [38]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target
#from sklearn.datasets.samples_generator import  make_classification
#X,y = make_classification(n_samples=6, n_features=5, n_informative=2, n_redundant=2, n_classes=2,
#                         n_clusters_per_class=2, scale=1.0, random_state=20)
#for x_, y_ in zip(X,y):
#    print(y, end=":")
#    print(x_)

# 2. 数据预处理

In [15]:
from sklearn import  preprocessing

In [22]:
#数据归一化
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
train_data = X
scaler = preprocessing.StandardScaler().fit(train_data)
scaler.transform(train_data)
#scaler.transform(test_data)

array([[-0.23118282, -1.71131893,  1.71770304,  1.19857094, -0.51965501],
       [ 0.39217125,  0.97024754, -1.00050853, -0.50892817,  1.77777141],
       [ 1.03980354, -0.86828257,  0.75345647,  1.36421794, -1.03981919],
       [-0.57862217,  0.08660018, -0.02668957, -0.4463902 , -0.4817237 ],
       [-1.75732374,  0.437955  , -0.2542427 , -1.49369334, -0.64979461],
       [ 1.13515394,  1.08479879, -1.18971871, -0.11377717,  0.91322111]])

In [30]:
#正则化
X = [[ 1., -1.,  2.], [ 2.,  0.,  0.],[ 0.,  1., -1.]]
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [36]:
# one-hot编码
data = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
encoder = preprocessing.OneHotEncoder().fit(data)
encoder.transform(data).toarray()

array([[1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 0.]])

# 3. 数据集拆分

In [39]:
from sklearn.model_selection import  train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3, random_state=2019)

# 4. 定义模型

In [ ]:
model.fit(X_train,y_train)
model.predict(X_test)

model.get_params()
model.score(data_X, data_y) #线性回归 R square; 分类问题: acc

4.1 线性回归

In [44]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(fit_intercept=True,normalize=False, copy_X=True, n_jobs=1)
'''
    fit_intercept：是否计算截距。False-模型没有截距
    normalize： 当fit_intercept设置为False时，该参数将被忽略。 如果为真，则回归前的回归系数X将通过减去平均值并除以l2-范数而归一化。
     n_jobs：指定线程数
'''

'\n    fit_intercept：是否计算截距。False-模型没有截距\n    normalize： 当fit_intercept设置为False时，该参数将被忽略。 如果为真，则回归前的回归系数X将通过减去平均值并除以l2-范数而归一化。\n     n_jobs：指定线程数\n'

 4.2 逻辑回归LR

In [45]:
from sklearn.linear_model import  LogisticRegression

In [46]:
model = LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0,fit_intercept=True,
                           intercept_scaling=1, class_weight=None, random_state=None, 
                           solver='liblinear', max_iter=100, multi_class='ovr',verbose=0, 
                           warm_start=False, n_jobs=1)

In [47]:
"""参数
---
    penalty：使用指定正则化项（默认：l2）
    dual: n_samples > n_features取False（默认）
    C：正则化强度的反，值越小正则化强度越大
    n_jobs: 指定线程数
    random_state：随机数生成器
    fit_intercept: 是否需要常量
"""

'参数\n---\n    penalty：使用指定正则化项（默认：l2）\n    dual: n_samples > n_features取False（默认）\n    C：正则化强度的反，值越小正则化强度越大\n    n_jobs: 指定线程数\n    random_state：随机数生成器\n    fit_intercept: 是否需要常量\n'

In [49]:
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [51]:
model.coef_

array([[ 0.35182749,  1.35898642, -2.0881359 , -0.97794004],
       [ 0.72886793, -1.86086716,  0.61161749, -1.69920569],
       [-1.57520998, -1.25719565,  2.05140514,  2.52676551]])

In [52]:
model.predict(X_test)

array([0, 0, 2, 1, 2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
       0, 1, 0, 0, 1, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2,
       2])

In [54]:
y_test

array([0, 0, 2, 1, 2, 0, 2, 0, 1, 2, 2, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
       0, 1, 0, 0, 1, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2,
       1])

In [53]:
model.score(X_test,y_test)

0.9333333333333333

4.3 朴素贝叶斯算法NB

In [55]:
from sklearn import naive_bayes

In [56]:
model = naive_bayes.GaussianNB()
model = naive_bayes.MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
model = naive_bayes.BernoulliNB(alpha=1.0, binarize=0.0, fit_prior=True, class_prior=None)
"""
文本分类问题常用MultinomialNB
参数
---
    alpha：平滑参数
    fit_prior：是否要学习类的先验概率；false-使用统一的先验概率
    class_prior: 是否指定类的先验概率；若指定则不能根据参数调整
    binarize: 二值化的阈值，若为None，则假设输入由二进制向量组成
"""

'\n文本分类问题常用MultinomialNB\n参数\n---\n    alpha：平滑参数\n    fit_prior：是否要学习类的先验概率；false-使用统一的先验概率\n    class_prior: 是否指定类的先验概率；若指定则不能根据参数调整\n    binarize: 二值化的阈值，若为None，则假设输入由二进制向量组成\n'

In [57]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.2222222222222222

4.4 决策树DT

In [58]:
from sklearn import tree

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [59]:
model = tree.DecisionTreeClassifier(criterion='gini', max_depth=None, min_samples_split=2, 
                                    min_samples_leaf=1, min_weight_fraction_leaf=0.0,
                                    max_features=None, random_state=None, max_leaf_nodes=None, 
                                    min_impurity_decrease=0.0, min_impurity_split=None,class_weight=None, 
                                    presort=False)

In [60]:
"""参数
---
    criterion ：特征选择准则gini/entropy
    max_depth：树的最大深度，None-尽量下分
    min_samples_split：分裂内部节点，所需要的最小样本树
    min_samples_leaf：叶子节点所需要的最小样本数
    max_features: 寻找最优分割点时的最大特征数
    max_leaf_nodes：优先增长到最大叶子节点数
    min_impurity_decrease：如果这种分离导致杂质的减少大于或等于这个值，则节点将被拆分。
"""

'参数\n---\n    criterion ：特征选择准则gini/entropy\n    max_depth：树的最大深度，None-尽量下分\n    min_samples_split：分裂内部节点，所需要的最小样本树\n    min_samples_leaf：叶子节点所需要的最小样本数\n    max_features: 寻找最优分割点时的最大特征数\n    max_leaf_nodes：优先增长到最大叶子节点数\n    min_impurity_decrease：如果这种分离导致杂质的减少大于或等于这个值，则节点将被拆分。\n'

4.5 支持向量机SVM

In [62]:
from sklearn.svm import  SVC

In [63]:
model = SVC(C=1.0, kernel='rbf', gamma='auto')

In [64]:
"""参数
---
    C：误差项的惩罚参数C
    gamma: 核相关系数。浮点数，If gamma is ‘auto’ then 1/n_features will be used instead.
"""

'参数\n---\n    C：误差项的惩罚参数C\n    gamma: 核相关系数。浮点数，If gamma is ‘auto’ then 1/n_features will be used instead.\n'

In [66]:
model.fit(X_train, y_train)
model.score(X_test, y_test)

1.0

4.6 k近邻算法KNN

In [67]:
from sklearn import neighbors

In [68]:
model = neighbors.KNeighborsClassifier(n_neighbors=5, n_jobs=1)
model = neighbors.KNeighborsRegressor(n_neighbors=5, n_jobs=1)

In [69]:
"""参数
---
    n_neighbors： 使用邻居的数目
    n_jobs：并行任务数
"""

'参数\n---\n    n_neighbors： 使用邻居的数目\n    n_jobs：并行任务数\n'

4.7 多层感知机（神经网络）

In [70]:
from sklearn.neural_network import  MLPClassifier

In [84]:
model = MLPClassifier(hidden_layer_sizes=(50,),activation='relu', solver='adam', alpha=0.0001)

In [85]:
"""参数
---
    hidden_layer_sizes: 元祖
    activation：激活函数
    solver ：优化算法{‘lbfgs’, ‘sgd’, ‘adam’}
    alpha：L2惩罚(正则化项)参数。
"""

'参数\n---\n    hidden_layer_sizes: 元祖\n    activation：激活函数\n    solver ：优化算法{‘lbfgs’, ‘sgd’, ‘adam’}\n    alpha：L2惩罚(正则化项)参数。\n'

In [86]:
model.fit(X_train,y_train)
model.score(X_test,y_test)

/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9555555555555556

# 5. 模型评估与选择篇

5.1 交叉验证

In [87]:
from sklearn.model_selection import cross_validate

In [90]:
cross_validate(model,X=X_train,y=y_train, scoring=None, n_jobs=1)

/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_sco

{'fit_time': array([0.10019732, 0.07443571, 0.07334208]),
 'score_time': array([0.00074911, 0.00041175, 0.00039506]),
 'test_score': array([1.        , 1.        , 0.91176471]),
 'train_score': array([0.97058824, 0.95774648, 1.        ])}

In [91]:
"""参数
---
    model：拟合数据的模型
    cv ： k-fold
    scoring: 打分参数-‘accuracy’、‘f1’、‘precision’、‘recall’ 、‘roc_auc’、'neg_log_loss'等等
"""

"参数\n---\n    model：拟合数据的模型\n    cv ： k-fold\n    scoring: 打分参数-‘accuracy’、‘f1’、‘precision’、‘recall’ 、‘roc_auc’、'neg_log_loss'等等\n"

5.2 检验曲线

In [92]:
from sklearn.model_selection import  validation_curve

In [94]:
#train_score, test_score = validation_curve(model, X,Y, param_name,param_range, cv=None, scoring=None, n_jobs=1)

"""参数
---
    model:用于fit和predict的对象
    X, y: 训练集的特征和标签
    param_name：将被改变的参数的名字
    param_range： 参数的改变范围
    cv：k-fold
   
返回值
---
   train_score: 训练集得分（array）
    test_score: 验证集得分（array）
"""

'参数\n---\n    model:用于fit和predict的对象\n    X, y: 训练集的特征和标签\n    param_name：将被改变的参数的名字\n    param_range： 参数的改变范围\n    cv：k-fold\n   \n返回值\n---\n   train_score: 训练集得分（array）\n    test_score: 验证集得分（array）\n'

# 6. 保存模型

In [95]:
import pickle

In [96]:
with open('model.pickle',"wb") as f:
    pickle.dump(model,f)

In [97]:
with open("model.pickle","rb") as f:
    model = pickle.load(f)
model.predict(X_test)

array([0, 0, 2, 1, 2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 2,
       0, 1, 0, 0, 1, 2, 0, 0, 2, 0, 0, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 2,
       1])

In [98]:
#sklearn 自带方法

In [102]:
from sklearn.externals import  joblib
joblib.dump(model,'model_jb.pickle')
model = joblib.load('model_jb.pickle')